# SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Remove IPC_LOCK (not allowed by OpenShift restricted SCC).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nico-ssh-console-rs
spec:
  template:
    spec:
      containers:
        - name: ssh-console-rs
          securityContext:
            capabilities:
              add: []
